### ISSUE TITLE
Use of pre- and suffix to distinguish between documents

### ISSUE THREAD

**Issue by ZheMann** [rkfg/gpt-2#5]
@rkfg for the past few days I have been downloading a bunch of data from wikipedia in order to train my model from scratch for the Dutch language. However, I'm wondering whether I would benefit from using `<|startoftext|>` and `<|endoftext|>` tags to distinguish between the wiki pages in my (large) .txt file, or that concatenating all pages together (so removing white lines) would be sufficient. Did you use these tags for your Russian book corpus?

**Comment by rkfg** [comment]
Theoretically, you might. The original model has `<|endoftext|>` markers but doesn't use them when generating text (i.e. it just continues to generate after encountering it). It's just another token for better readability but the model might learn that texts before and after that token are not related.

I didn't use any tags other than `<|n|>` for new lines because SentencePiece doesn't add such a token to the dictionary automatically.

**Comment by ZheMann** [comment]
Thanks for the quick reply, I really appreciate. So, I think I only have to add the `<|startoftext|>` to the `--user_defined_symbols` in order to make it work properly.

> I didn't use any tags other than <|n|> for new lines because SentencePiece doesn't add such a token to the dictionary automatically.

Also thanks for mentioning this, as I wouldn't have thought of this.

**Comment by rkfg** [comment]
I don't think you need a special token to mark the beginning of the text. They're all concatenated so every text's end is another text's beginning and the train script samples it all randomly. So sometimes you'll have `<|endoftext|>` in the middle of a sample. It's the network's problem to figure out text boundaries and you don't want to complicate it even more with two tokens instead of just one.
